--- #YAML:1.0
name:               Bot-BasicBot-Pluggable-Module-NorskEngelsk
version:            0.02
abstract:           Translate Norwegian into English
author:
    - Cosimo Streppone <cosimo@cpan.org>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    Bot::BasicBot::Pluggable:  0
    CGI:                  0
    HTML::Entities:       0
    LWP::Simple:          0
    LWP::UserAgent:       0
    Test::More:           0
    WebService::Google::Language:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.47_01
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
